global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'drift-monitor'
    scrape_interval: 1m
    metrics_path: /metrics
    static_configs:
      - targets: ['monitor:5445']

#remote_write:
#  - url: '<Your Prometheus remote_write endpoint>'
#    basic_auth:
#      username: '<Your Grafana Username>'
#      password: '<Your Grafana API key>'